# -*- coding: utf-8 -*-
"""heart_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1INOTebQwnc6YTYd4yi6H6sNsEDe8dT3W
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

data = pd.read_csv('heart.csv')
data

"""#EDA"""

data.columns

data.info()

data.describe()

data.duplicated().sum()

data['HeartDisease'].value_counts().plot(kind = 'bar')

data.isnull().sum()

def ploting(var,num):
  plt.subplot(2,2,num)
  sns.histplot(data[var],kde=True)
ploting('Age',1)
ploting('RestingBP',2)
ploting('Cholesterol',3)
ploting('MaxHR',4)

data['Cholesterol'].value_counts()

ch_mean = data.loc[data['Cholesterol'] != 0,'Cholesterol'].mean()
data['Cholesterol'] = data['Cholesterol'].replace(0,ch_mean)
data['Cholesterol'] = data['Cholesterol'].round(2)

ch_mean

resting_bp_mean = data.loc[data['RestingBP'] != 0,'RestingBP'].mean()
data['RestingBP'] = data['RestingBP'].replace(0,resting_bp_mean)
data['RestingBP']

def ploting(var,num):
  plt.subplot(2,2,num)
  sns.histplot(data[var],kde=True)
ploting('Age',1)
ploting('RestingBP',2)
ploting('Cholesterol',3)
ploting('MaxHR',4)

pip install sheryanalysis==0.1.0

import sheryanalysis as sha
sha.analyze(data)

sns.countplot(x=data['Sex'])

sns.countplot(x=data['ChestPainType'], hue=data['HeartDisease'])

sns.countplot(x=data['Sex'], hue=data['HeartDisease'])

sns.boxplot(x=data['HeartDisease'],y=data['Cholesterol'])

"""#data preproceing"""

df_encode = pd.get_dummies(data,drop_first=True)
df_encode

df_encode = df_encode.astype(int)
df_encode

from sklearn.preprocessing import StandardScaler
numeric_cols = ['Age','RestingBP','Cholesterol','MaxHR']
scaler = StandardScaler()
df_encode[numeric_cols] = scaler.fit_transform(df_encode[numeric_cols])

df_encode.head()